const spells = [
    {
        "name": "Animate Dead Rune",
        "spell_id": "animatedeadrune",
        "formula": "adana mort",
        "level": 27,
        "mana": 600,
        "price": 1200,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": true
    },
    {
        "name": "Annihilation",
        "spell_id": "annihilation",
        "formula": "exori gran ico",
        "level": 110,
        "mana": 300,
        "price": 20000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Apprentice's Strike",
        "spell_id": "apprenticestrike",
        "formula": "exori min flam",
        "level": 8,
        "mana": 6,
        "price": 0,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Arrow Call",
        "spell_id": "arrowcall",
        "formula": "exevo infir con",
        "level": 1,
        "mana": 10,
        "price": 0,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Avalanche Rune",
        "spell_id": "avalancherune",
        "formula": "adori mas frigo",
        "level": 30,
        "mana": 530,
        "price": 1200,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Avatar of Light",
        "spell_id": "avataroflight",
        "formula": "uteta res sac",
        "level": 0,
        "mana": 1500,
        "price": 0,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Avatar of Nature",
        "spell_id": "avatarofnature",
        "formula": "uteta res dru",
        "level": 0,
        "mana": 2200,
        "price": 0,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Avatar of Steel",
        "spell_id": "avatarofsteel",
        "formula": "uteta res eq",
        "level": 0,
        "mana": 800,
        "price": 0,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Avatar of Storm",
        "spell_id": "avatarofstorm",
        "formula": "uteta res ven",
        "level": 0,
        "mana": 2200,
        "price": 0,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Berserk",
        "spell_id": "berserk",
        "formula": "exori",
        "level": 35,
        "mana": 115,
        "price": 2500,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Blood Rage",
        "spell_id": "bloodrage",
        "formula": "utito tempo",
        "level": 60,
        "mana": 290,
        "price": 8000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Bruise Bane",
        "spell_id": "bruisebane",
        "formula": "exura infir ico",
        "level": 1,
        "mana": 10,
        "price": 0,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Brutal Strike",
        "spell_id": "brutalstrike",
        "formula": "exori ico",
        "level": 16,
        "mana": 30,
        "price": 1000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Buzz",
        "spell_id": "buzz",
        "formula": "exori infir vis",
        "level": 1,
        "mana": 6,
        "price": 0,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Cancel Invisibility",
        "spell_id": "cancelinvisibility",
        "formula": "exana ina",
        "level": 26,
        "mana": 200,
        "price": 1600,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Cancel Magic Shield",
        "spell_id": "cancelmagicshield",
        "formula": "exana vita",
        "level": 14,
        "mana": 50,
        "price": 450,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Challenge",
        "spell_id": "challenge",
        "formula": "exeta res",
        "level": 20,
        "mana": 40,
        "price": 2000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Chameleon Rune",
        "spell_id": "chameleonrune",
        "formula": "adevo ina",
        "level": 27,
        "mana": 600,
        "price": 1300,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Charge",
        "spell_id": "charge",
        "formula": "utani tempo hur",
        "level": 25,
        "mana": 100,
        "price": 1300,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Chill Out",
        "spell_id": "chillout",
        "formula": "exevo infir frigo hur",
        "level": 1,
        "mana": 8,
        "price": 0,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Chivalrous Challenge",
        "spell_id": "chivalrouschallenge",
        "formula": "exeta amp res",
        "level": 150,
        "mana": 80,
        "price": 250000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Conjure Arrow",
        "spell_id": "conjurearrow",
        "formula": "exevo con",
        "level": 13,
        "mana": 100,
        "price": 450,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Conjure Explosive Arrow",
        "spell_id": "conjureexplosivearrow",
        "formula": "exevo con flam",
        "level": 25,
        "mana": 290,
        "price": 1000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Conjure Wand of Darkness",
        "spell_id": "conjurewandofdarkness",
        "formula": "exevo gran mort",
        "level": 41,
        "mana": 250,
        "price": 5000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Convince Creature Rune",
        "spell_id": "convincecreaturerune",
        "formula": "adeta sio",
        "level": 16,
        "mana": 200,
        "price": 800,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Creature Illusion",
        "spell_id": "creatureillusion",
        "formula": "utevo res ina \"creature\"",
        "level": 23,
        "mana": 100,
        "price": 1000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Cure Bleeding",
        "spell_id": "curebleeding",
        "formula": "exana kor",
        "level": 45,
        "mana": 30,
        "price": 2500,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Cure Burning",
        "spell_id": "cureburning",
        "formula": "exana flam",
        "level": 30,
        "mana": 30,
        "price": 2000,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Cure Curse",
        "spell_id": "curecurse",
        "formula": "exana mort",
        "level": 80,
        "mana": 40,
        "price": 6000,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Cure Electrification",
        "spell_id": "cureelectrification",
        "formula": "exana vis",
        "level": 22,
        "mana": 30,
        "price": 1000,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Cure Poison",
        "spell_id": "curepoison",
        "formula": "exana pox",
        "level": 10,
        "mana": 30,
        "price": 150,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Cure Poison Rune",
        "spell_id": "curepoisonrune",
        "formula": "adana pox",
        "level": 15,
        "mana": 200,
        "price": 600,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Curse",
        "spell_id": "curse",
        "formula": "utori mort",
        "level": 75,
        "mana": 30,
        "price": 6000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Death Strike",
        "spell_id": "deathstrike",
        "formula": "exori mort",
        "level": 16,
        "mana": 20,
        "price": 800,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Destroy Field Rune",
        "spell_id": "destroyfieldrune",
        "formula": "adito grav",
        "level": 17,
        "mana": 120,
        "price": 700,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Disintegrate Rune",
        "spell_id": "disintegraterune",
        "formula": "adito tera",
        "level": 21,
        "mana": 200,
        "price": 900,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": true
    },
    {
        "name": "Divine Caldera",
        "spell_id": "divinecaldera",
        "formula": "exevo mas san",
        "level": 50,
        "mana": 160,
        "price": 3000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Divine Dazzle",
        "spell_id": "divinedazzle",
        "formula": "exana amp res",
        "level": 250,
        "mana": 80,
        "price": 250000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Divine Empowerment",
        "spell_id": "divineempowerment",
        "formula": "utevo grav san",
        "level": 0,
        "mana": 500,
        "price": 0,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Divine Grenade",
        "spell_id": "divinegrenade",
        "formula": "exevo tempo mas san",
        "level": 0,
        "mana": 160,
        "price": 0,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Divine Healing",
        "spell_id": "divinehealing",
        "formula": "exura san",
        "level": 35,
        "mana": 160,
        "price": 3000,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Divine Missile",
        "spell_id": "divinemissile",
        "formula": "exori san",
        "level": 40,
        "mana": 20,
        "price": 1800,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Electrify",
        "spell_id": "electrify",
        "formula": "utori vis",
        "level": 34,
        "mana": 30,
        "price": 2500,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Enchant Party",
        "spell_id": "enchantparty",
        "formula": "utori mas sio",
        "level": 32,
        "mana": -1,
        "price": 4000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Enchant Spear",
        "spell_id": "enchantspear",
        "formula": "exeta con",
        "level": 45,
        "mana": 350,
        "price": 2000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Energy Beam",
        "spell_id": "energybeam",
        "formula": "exevo vis lux",
        "level": 23,
        "mana": 40,
        "price": 1000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Energy Bomb Rune",
        "spell_id": "energybombrune",
        "formula": "adevo mas vis",
        "level": 37,
        "mana": 880,
        "price": 2300,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": true
    },
    {
        "name": "Energy Field Rune",
        "spell_id": "energyfieldrune",
        "formula": "adevo grav vis",
        "level": 18,
        "mana": 320,
        "price": 700,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Energy Strike",
        "spell_id": "energystrike",
        "formula": "exori vis",
        "level": 12,
        "mana": 20,
        "price": 800,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Energy Wall Rune",
        "spell_id": "energywallrune",
        "formula": "adevo mas grav vis",
        "level": 41,
        "mana": 1000,
        "price": 2500,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Energy Wave",
        "spell_id": "energywave",
        "formula": "exevo vis hur",
        "level": 38,
        "mana": 170,
        "price": 2500,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Envenom",
        "spell_id": "envenom",
        "formula": "utori pox",
        "level": 50,
        "mana": 30,
        "price": 6000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Eternal Winter",
        "spell_id": "eternalwinter",
        "formula": "exevo gran mas frigo",
        "level": 60,
        "mana": 1050,
        "price": 8000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Ethereal Spear",
        "spell_id": "etherealspear",
        "formula": "exori con",
        "level": 23,
        "mana": 25,
        "price": 1100,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Executioner's Throw",
        "spell_id": "executionersthrow",
        "formula": "exori amp kor",
        "level": 0,
        "mana": 225,
        "price": 0,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Explosion Rune",
        "spell_id": "explosionrune",
        "formula": "adevo mas hur",
        "level": 31,
        "mana": 570,
        "price": 1800,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Expose Weakness",
        "spell_id": "exposeweakness",
        "formula": "exori moe",
        "level": 275,
        "mana": 400,
        "price": 400000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Fair Wound Cleansing",
        "spell_id": "fairwoundcleansing",
        "formula": "exura med ico",
        "level": 300,
        "mana": 90,
        "price": 500000,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Fierce Berserk",
        "spell_id": "fierceberserk",
        "formula": "exori gran",
        "level": 90,
        "mana": 340,
        "price": 7500,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Find Fiend",
        "spell_id": "findfiend",
        "formula": "exiva moe res",
        "level": 25,
        "mana": 20,
        "price": 1000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Find Person",
        "spell_id": "findperson",
        "formula": "exiva \"name\"",
        "level": 8,
        "mana": 20,
        "price": 80,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Fire Bomb Rune",
        "spell_id": "firebombrune",
        "formula": "adevo mas flam",
        "level": 27,
        "mana": 600,
        "price": 1500,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Fire Field Rune",
        "spell_id": "firefieldrune",
        "formula": "adevo grav flam",
        "level": 15,
        "mana": 240,
        "price": 500,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Fire Wall Rune",
        "spell_id": "firewallrune",
        "formula": "adevo mas grav flam",
        "level": 33,
        "mana": 780,
        "price": 2000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Fire Wave",
        "spell_id": "firewave",
        "formula": "exevo flam hur",
        "level": 18,
        "mana": 25,
        "price": 850,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Fireball Rune",
        "spell_id": "fireballrune",
        "formula": "adori flam",
        "level": 27,
        "mana": 460,
        "price": 1600,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": true
    },
    {
        "name": "Flame Strike",
        "spell_id": "flamestrike",
        "formula": "exori flam",
        "level": 14,
        "mana": 20,
        "price": 800,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Food",
        "spell_id": "food",
        "formula": "exevo pan",
        "level": 14,
        "mana": 120,
        "price": 300,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Front Sweep",
        "spell_id": "frontsweep",
        "formula": "exori min",
        "level": 70,
        "mana": 200,
        "price": 4000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Great Death Beam",
        "spell_id": "greatdeathbeam",
        "formula": "exevo max mort",
        "level": 0,
        "mana": 140,
        "price": 0,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Great Energy Beam",
        "spell_id": "greatenergybeam",
        "formula": "exevo gran vis lux",
        "level": 29,
        "mana": 110,
        "price": 1800,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Great Fire Wave",
        "spell_id": "greatfirewave",
        "formula": "exevo gran flam hur",
        "level": 38,
        "mana": 120,
        "price": 25000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Great Fireball Rune",
        "spell_id": "greatfireballrune",
        "formula": "adori mas flam",
        "level": 30,
        "mana": 530,
        "price": 1200,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Great Light",
        "spell_id": "greatlight",
        "formula": "utevo gran lux",
        "level": 13,
        "mana": 60,
        "price": 500,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Groundshaker",
        "spell_id": "groundshaker",
        "formula": "exori mas",
        "level": 33,
        "mana": 160,
        "price": 1500,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Haste",
        "spell_id": "haste",
        "formula": "utani hur",
        "level": 14,
        "mana": 60,
        "price": 600,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Heal Friend",
        "spell_id": "healfriend",
        "formula": "exura sio \"name\"",
        "level": 18,
        "mana": 120,
        "price": 800,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Heal Party",
        "spell_id": "healparty",
        "formula": "utura mas sio",
        "level": 32,
        "mana": -1,
        "price": 4000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Heavy Magic Missile Rune",
        "spell_id": "heavymagicmissilerune",
        "formula": "adori vis",
        "level": 25,
        "mana": 350,
        "price": 1500,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Hell's Core",
        "spell_id": "hellscore",
        "formula": "exevo gran mas flam",
        "level": 60,
        "mana": 1100,
        "price": 8000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Holy Flash",
        "spell_id": "holyflash",
        "formula": "utori san",
        "level": 70,
        "mana": 30,
        "price": 7500,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Holy Missile Rune",
        "spell_id": "holymissilerune",
        "formula": "adori san",
        "level": 27,
        "mana": 300,
        "price": 1600,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": true
    },
    {
        "name": "Ice Burst",
        "spell_id": "iceburst",
        "formula": "exevo ulus frigo",
        "level": 0,
        "mana": 230,
        "price": 0,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Ice Strike",
        "spell_id": "icestrike",
        "formula": "exori frigo",
        "level": 15,
        "mana": 20,
        "price": 800,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Ice Wave",
        "spell_id": "icewave",
        "formula": "exevo frigo hur",
        "level": 18,
        "mana": 25,
        "price": 850,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Icicle Rune",
        "spell_id": "iciclerune",
        "formula": "adori frigo",
        "level": 28,
        "mana": 460,
        "price": 1700,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": true
    },
    {
        "name": "Ignite",
        "spell_id": "ignite",
        "formula": "utori flam",
        "level": 26,
        "mana": 30,
        "price": 1500,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Inflict Wound",
        "spell_id": "inflictwound",
        "formula": "utori kor",
        "level": 40,
        "mana": 30,
        "price": 2500,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Intense Healing",
        "spell_id": "intensehealing",
        "formula": "exura gran",
        "level": 20,
        "mana": 70,
        "price": 350,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Intense Healing Rune",
        "spell_id": "intensehealingrune",
        "formula": "adura gran",
        "level": 15,
        "mana": 120,
        "price": 600,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Intense Recovery",
        "spell_id": "intenserecovery",
        "formula": "utura gran",
        "level": 100,
        "mana": 165,
        "price": 10000,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Intense Wound Cleansing",
        "spell_id": "intensewoundcleansing",
        "formula": "exura gran ico",
        "level": 80,
        "mana": 200,
        "price": 6000,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Invisible",
        "spell_id": "invisible",
        "formula": "utana vid",
        "level": 35,
        "mana": 440,
        "price": 2000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Lesser Ethereal Spear",
        "spell_id": "lesseretherealspear",
        "formula": "exori infir con",
        "level": 0,
        "mana": 6,
        "price": 0,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Lesser Front Sweep",
        "spell_id": "lesserfrontsweep",
        "formula": "exori infir min",
        "level": 0,
        "mana": 6,
        "price": 0,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Levitate",
        "spell_id": "levitate",
        "formula": "exani hur \"up|down\"",
        "level": 12,
        "mana": 50,
        "price": 500,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Light",
        "spell_id": "light",
        "formula": "utevo lux",
        "level": 8,
        "mana": 20,
        "price": 0,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Light Healing",
        "spell_id": "lighthealing",
        "formula": "exura",
        "level": 8,
        "mana": 20,
        "price": 0,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Light Magic Missile Rune",
        "spell_id": "lightmagicmissilerune",
        "formula": "adori min vis",
        "level": 15,
        "mana": 120,
        "price": 500,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Lightning",
        "spell_id": "lightning",
        "formula": "exori amp vis",
        "level": 55,
        "mana": 60,
        "price": 5000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Magic Patch",
        "spell_id": "magicpatch",
        "formula": "exura infir",
        "level": 1,
        "mana": 6,
        "price": 0,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Magic Rope",
        "spell_id": "magicrope",
        "formula": "exani tera",
        "level": 9,
        "mana": 20,
        "price": 200,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Magic Shield",
        "spell_id": "magicshield",
        "formula": "utamo vita",
        "level": 14,
        "mana": 50,
        "price": 450,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Magic Wall Rune",
        "spell_id": "magicwallrune",
        "formula": "adevo grav tera",
        "level": 32,
        "mana": 750,
        "price": 2100,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": true
    },
    {
        "name": "Mass Healing",
        "spell_id": "masshealing",
        "formula": "exura gran mas res",
        "level": 36,
        "mana": 150,
        "price": 2200,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Mud Attack",
        "spell_id": "mudattack",
        "formula": "exori infir tera",
        "level": 1,
        "mana": 6,
        "price": 0,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Nature's Embrace",
        "spell_id": "naturesembrace",
        "formula": "exura gran sio \"name\"",
        "level": 275,
        "mana": 400,
        "price": 500000,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Paralyse Rune",
        "spell_id": "paralyserune",
        "formula": "adana ani",
        "level": 54,
        "mana": 1400,
        "price": 1900,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": true
    },
    {
        "name": "Physical Strike",
        "spell_id": "physicalstrike",
        "formula": "exori moe ico",
        "level": 16,
        "mana": 20,
        "price": 800,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Poison Bomb Rune",
        "spell_id": "poisonbombrune",
        "formula": "adevo mas pox",
        "level": 25,
        "mana": 520,
        "price": 1000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": true
    },
    {
        "name": "Poison Field Rune",
        "spell_id": "poisonfieldrune",
        "formula": "adevo grav pox",
        "level": 14,
        "mana": 200,
        "price": 300,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Poison Wall Rune",
        "spell_id": "poisonwallrune",
        "formula": "adevo mas grav pox",
        "level": 29,
        "mana": 640,
        "price": 1600,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Protect Party",
        "spell_id": "protectparty",
        "formula": "utamo mas sio",
        "level": 32,
        "mana": -1,
        "price": 4000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Protector",
        "spell_id": "protector",
        "formula": "utamo tempo",
        "level": 55,
        "mana": 200,
        "price": 6000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Rage of the Skies",
        "spell_id": "rageoftheskies",
        "formula": "exevo gran mas vis",
        "level": 55,
        "mana": 600,
        "price": 6000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Recovery",
        "spell_id": "recovery",
        "formula": "utura",
        "level": 50,
        "mana": 75,
        "price": 4000,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Restoration",
        "spell_id": "restoration",
        "formula": "exura max vita",
        "level": 300,
        "mana": 260,
        "price": 500000,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Salvation",
        "spell_id": "salvation",
        "formula": "exura gran san",
        "level": 60,
        "mana": 210,
        "price": 8000,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Sap Strength",
        "spell_id": "sapstrength",
        "formula": "exori kor",
        "level": 175,
        "mana": 300,
        "price": 200000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Scorch",
        "spell_id": "scorch",
        "formula": "exevo infir flam hur",
        "level": 1,
        "mana": 8,
        "price": 0,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Sharpshooter",
        "spell_id": "sharpshooter",
        "formula": "utito tempo san",
        "level": 60,
        "mana": 450,
        "price": 8000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Soulfire Rune",
        "spell_id": "soulfirerune",
        "formula": "adevo res flam",
        "level": 27,
        "mana": 420,
        "price": 1800,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": true
    },
    {
        "name": "Stalagmite Rune",
        "spell_id": "stalagmiterune",
        "formula": "adori tera",
        "level": 24,
        "mana": 350,
        "price": 1400,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Stone Shower Rune",
        "spell_id": "stoneshowerrune",
        "formula": "adori mas tera",
        "level": 28,
        "mana": 430,
        "price": 1100,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": true
    },
    {
        "name": "Strong Energy Strike",
        "spell_id": "strongenergystrike",
        "formula": "exori gran vis",
        "level": 80,
        "mana": 60,
        "price": 7500,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Strong Ethereal Spear",
        "spell_id": "strongetherealspear",
        "formula": "exori gran con",
        "level": 90,
        "mana": 55,
        "price": 10000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Strong Flame Strike",
        "spell_id": "strongflamestrike",
        "formula": "exori gran flam",
        "level": 70,
        "mana": 60,
        "price": 6000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Strong Haste",
        "spell_id": "stronghaste",
        "formula": "utani gran hur",
        "level": 20,
        "mana": 100,
        "price": 1300,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Strong Ice Strike",
        "spell_id": "strongicestrike",
        "formula": "exori gran frigo",
        "level": 80,
        "mana": 60,
        "price": 6000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Strong Ice Wave",
        "spell_id": "strongicewave",
        "formula": "exevo gran frigo hur",
        "level": 40,
        "mana": 170,
        "price": 7500,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Strong Terra Strike",
        "spell_id": "strongterrastrike",
        "formula": "exori gran tera",
        "level": 70,
        "mana": 60,
        "price": 6000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Sudden Death Rune",
        "spell_id": "suddendeathrune",
        "formula": "adori gran mort",
        "level": 45,
        "mana": 985,
        "price": 3000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Summon Creature",
        "spell_id": "summoncreature",
        "formula": "utevo res \"creature\"",
        "level": 25,
        "mana": -1,
        "price": 2000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Summon Druid Familiar",
        "spell_id": "summondruid",
        "formula": "utevo gran res dru",
        "level": 200,
        "mana": 3000,
        "price": 50000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Summon Knight Familiar",
        "spell_id": "summonknight",
        "formula": "utevo gran res eq",
        "level": 200,
        "mana": 1000,
        "price": 50000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Summon Paladin Familiar",
        "spell_id": "summonpaladin",
        "formula": "utevo gran res sac",
        "level": 200,
        "mana": 2000,
        "price": 50000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Summon Sorcerer Familiar",
        "spell_id": "summonsorcerer",
        "formula": "utevo gran res ven",
        "level": 200,
        "mana": 3000,
        "price": 50000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Swift Foot",
        "spell_id": "swiftfoot",
        "formula": "utamo tempo san",
        "level": 55,
        "mana": 400,
        "price": 6000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Terra Burst",
        "spell_id": "terraburst",
        "formula": "exevo ulus tera",
        "level": 0,
        "mana": 230,
        "price": 0,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Terra Strike",
        "spell_id": "terrastrike",
        "formula": "exori tera",
        "level": 13,
        "mana": 20,
        "price": 800,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Terra Wave",
        "spell_id": "terrawave",
        "formula": "exevo tera hur",
        "level": 38,
        "mana": 170,
        "price": 2500,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Thunderstorm Rune",
        "spell_id": "thunderstormrune",
        "formula": "adori mas vis",
        "level": 28,
        "mana": 430,
        "price": 1100,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": true
    },
    {
        "name": "Train Party",
        "spell_id": "trainparty",
        "formula": "utito mas sio",
        "level": 32,
        "mana": -1,
        "price": 4000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Ultimate Energy Strike",
        "spell_id": "ultimateenergystrike",
        "formula": "exori max vis",
        "level": 100,
        "mana": 100,
        "price": 15000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Ultimate Flame Strike",
        "spell_id": "ultimateflamestrike",
        "formula": "exori max flam",
        "level": 90,
        "mana": 100,
        "price": 15000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Ultimate Healing",
        "spell_id": "ultimatehealing",
        "formula": "exura vita",
        "level": 30,
        "mana": 160,
        "price": 1000,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Ultimate Healing Rune",
        "spell_id": "ultimatehealingrune",
        "formula": "adura vita",
        "level": 24,
        "mana": 400,
        "price": 1500,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": false
    },
    {
        "name": "Ultimate Ice Strike",
        "spell_id": "ultimateicestrike",
        "formula": "exori max frigo",
        "level": 100,
        "mana": 100,
        "price": 15000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Ultimate Light",
        "spell_id": "ultimatelight",
        "formula": "utevo vis lux",
        "level": 26,
        "mana": 140,
        "price": 1600,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Ultimate Terra Strike",
        "spell_id": "ultimateterrastrike",
        "formula": "exori max tera",
        "level": 90,
        "mana": 100,
        "price": 15000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Whirlwind Throw",
        "spell_id": "whirlwindthrow",
        "formula": "exori hur",
        "level": 28,
        "mana": 40,
        "price": 1500,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    },
    {
        "name": "Wild Growth Rune",
        "spell_id": "wildgrowthrune",
        "formula": "adevo grav vita",
        "level": 27,
        "mana": 600,
        "price": 2000,
        "group_attack": false,
        "group_healing": false,
        "group_support": true,
        "type_instant": false,
        "type_rune": true,
        "premium_only": true
    },
    {
        "name": "Wound Cleansing",
        "spell_id": "woundcleansing",
        "formula": "exura ico",
        "level": 8,
        "mana": 40,
        "price": 0,
        "group_attack": false,
        "group_healing": true,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": false
    },
    {
        "name": "Wrath of Nature",
        "spell_id": "wrathofnature",
        "formula": "exevo gran mas tera",
        "level": 55,
        "mana": 700,
        "price": 6000,
        "group_attack": true,
        "group_healing": false,
        "group_support": false,
        "type_instant": true,
        "type_rune": false,
        "premium_only": true
    }
]
